[tool.poetry]
name = "things-cloud-api"
version = "0.1.0"
description = ""
authors = ["disrupted <hi@salomonpopp.me>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
loguru = "^0.5.3"
dataclasses-json = "^0.5.4"
orjson = "^3.5.3"
pydantic = "^1.8.2"
shortuuid = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-mock = "^3.6.1"
pytest-clarity = "^1.0.1"
freezegun = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
